
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]
  errors:
    avoid_function_literals_in_foreach_calls: ignore
    avoid_renaming_method_parameters: ignore
    curly_braces_in_flow_control_structures: ignore
    library_prefixes: ignore
    missing_required_param: warning
    missing_return: warning
    no_logic_in_create_state: ignore
    omit_local_variable_types: ignore
    prefer_function_declarations_over_variables: ignore
    sort_child_properties_last: ignore
    sort_pub_dependencies: ignore
    todo: ignore
    unnecessary_string_escapes: ignore
