name: newquist_dev
description: Website for myself
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  provider: ^6.0.3
  scrollable_positioned_list: ^0.3.2
  url_strategy: 0.2.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/