name: newquist_dev
description: Website for myself
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  mockito: ^5.2.0
  provider: ^6.0.3
  scrollable_positioned_list: ^0.3.2
  url_launcher: ^6.1.3
  url_strategy: 0.2.0-nullsafety.0
  firebase_core: ^1.18.0
  firebase_analytics: ^9.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/